### ISSUE TITLE
Merge highscore.json with data.json

### ISSUE THREAD

**Issue by R0merol** [R0merol/Number-Game-v0.1#30]
highscore.json contains highscores, while data.json currently contains achievement data. I intend to combine both of them so everything is tidier. But this will mean refactoring highscores code across the project to make it work. I've made a placeholder highscores data on data.json as an example.

**Comment by Aragorn-64** [comment]
Hi @R0merol, I'd like to work on this :)

**Comment by R0merol** [comment]
Good luck 💯

**Comment by R0merol** [comment]
Can you put data.json in .gitingore as well just like highscore.json so every time there's a fresh installation, everything resets?

**Comment by Lyeriff** [comment]
I would also like to work on this.

**Comment by Lyeriff** [comment]
@R0merol Hey, I've merged highscore.json and data.json into data.json. Also instead of the gitignore method I have made it so that when the game is run for the first time it creates a fresh data.json, was wondering if that is okay?

**Comment by R0merol** [comment]
> I have made it so that when the game is run for the first time it creates a fresh data.json

Yess, that's exactly what I'm going for. Do note that this issue is already assigned to @Aragorn-64, so you guys might wanna communicate on that

**Comment by Lyeriff** [comment]
Hey @Aragorn-64 how far in are you into resolving this issue?

**Comment by Aragorn-64** [comment]
Hi @Lyeriff, I was a bit busy and had only gotten to reading and understanding the code base and what this problem needed. Did you already solve the issue?

**Comment by Aragorn-64** [comment]
@R0merol Can i still try and work on the issue? It would be a learning experience for me (as I was unfamiliar with .json and larger python projects)

**Comment by R0merol** [comment]
@Aragorn-64 The issue has been resolved. I'm not sure if we could implement anything else regarding the data.json, but stay tuned because I might get more ideas for this!

**Comment by Aragorn-64** [comment]
Okay @R0merol
