### ISSUE TITLE
use black and isort

### ISSUE THREAD

**Issue by Joshix-1** [R0merol/Number-Game-v0.1#42]
auto-format the code with [black](https://github.com/psf/black) and [isort](https://github.com/PyCQA/isort)

**Comment by R0merol** [comment]
So, using black and isort automatically formats the code after saving it? Will using autosave mess with the code while I'm coding it? I have not used it before so I don't know how it works

**Comment by Joshix-1** [comment]
You can configure it how you like. I would recommend running either on auto save or manually.
They only mess with the code when you run them

**Comment by colderinit** [comment]
Hi there! I have begun some work in a fork towards this issue! https://github.com/colderinit/Number-Game-v0.1/tree/action-isrt-blck

**Comment by colderinit** [comment]
I just read the CONTRIBUTING.md... @R0merol, could you assign me this issue? :)

**Comment by R0merol** [comment]
Closed for now, will reopen if there are issues
