### ISSUE TITLE
Change the game's icon

### ISSUE THREAD

**Issue by R0merol** [R0merol/Number-Game-v0.1#52]
I'd like to change the game's icon to this icon. Here's the [download link](https://drive.google.com/file/d/1fpCX-h41rl9XznwJa6mau8_OpiTFhO3R/view?usp=sharing) for the icon.

![number_game](https://user-images.githubusercontent.com/87220004/197554526-4a9aa1db-2144-4808-a432-b7125c1cc226.png)

**Comment by zafar-hussain** [comment]
Hi @R0merol,

please assign this issue to me

cheers
